# Generated by Django 4.1.5 on 2023-01-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='desc',
            field=models.CharField(default='Description', max_length=250),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
