# Generated by Django 4.1.5 on 2023-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.CharField(default='', max_length=250),
        ),
    ]
