# Generated by Django 4.1.5 on 2023-01-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_desc_alter_entry_text_alter_topic_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
